<?php
    function encrypt_menu() {
        $items['encrpyt'] = array(
            'title' => 'Encrpyt',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('encrypt_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['encrypt_success_page'] = array(
            'title' => 'Succesfully Encrypted',
            'page callback' => 'encrypt_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function encrypt_form() {
        $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Enter a number for the shift value.'),
            '#required' => TRUE,
        );
        $form['direction'] = array(
            '#title' => 'Direction',
            '#type' => 'textfield',
            '#description' => t('Enter the direction you would like to shift.'),
            '#required' => TRUE,
        );
        $form['phrase'] = array(
            '#title' => 'Phrase',
            '#type' => 'textfield',
            '#description' => t('Enter a phrase to be encrpyted.')
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Encrypt!',
        );
        return $form;
    }

    function encrypt_form_submit($form, &$form_state){
        $shift_value = $form_state['values']['shift_value'];
        $direction = strtolower($form_state['values']['direction']);
        $phrase = $form_state['values']['phrase'];
        $phrase_words = explode(" ", $phrase);

        $alphabet = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

        $keys = array_flip($alphabet); // converts the array from its letter values to its number keys
        $phrase = str_split($phrase); //splits the string into an array of each letter in the phrase


        foreach ($phrase_words as $word){
            $i = 0; // initializing starting position of loop
            $word = str_split($word);
            $word_length = sizeof($word);

            $encrypted_words = array();

            if ($direction == 'right'){
                do {
                    $encrypted_word .= $alphabet[($keys[$word[$i]] + $shift_value)%26];
                    $i++;
                } while($i < $word_length);
            } else {
                do {
                    $encrypted_word .= $alphabet[($keys[$word[$i]] - $shift_value)%26];
                    $i++;
                } while($i < $word_length);
            }
            array_push($encrypted_words, $encrypted_word);
        }
        $encrypted_phrase = implode(" ", $encrypted_words);
        $_SESSION['encrypted_output'] = $encrypted_phrase;
        $form_state['redirect'] = 'encrypt_success_page';
    }

    function encrypt_success(){
        $new_phrase = $_SESSION['encrypted_output'];
        var_dump($new_phrase);
        return $new_phrase;
    }
